name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - ''

jobs:
  test-java:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/java/Dockerfile
          tags: inga-java
      - name: Build Docker image for test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/docker/Dockerfile
          tags: test-inga-java
          build-args: |
            BASE_IMAGE=inga-java
      - name: Run tests
        run: |
          docker run test-inga-java -c "
            (cd /inga/test/fixtures/spring-boot-realworld-example-app && ./gradlew compileJava)
            (cd /inga/test/fixtures/spring-tutorials/lightrun && mvn compile)
            (cd /inga/test/fixtures/spring-tutorials/guava-modules && mvn compile)

            ros -s fiveam -e \"
              (ql:quickload :inga)
              (handler-case (asdf:test-system :inga)
                (error () (uiop:quit 1)))
              (ql:quickload :inga/test-jvm)
              (handler-case (asdf:test-system :inga/test-jvm)
                (error () (uiop:quit 1)))\""

  test-typescript:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/typescript/Dockerfile
          tags: inga-typescript
      - name: Build Docker image for test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/workflows/docker/Dockerfile
          tags: test-inga-typescript
          build-args: |
            BASE_IMAGE=inga-typescript
      - name: Run tests
        run: |
          docker run test-inga-typescript -c "
            ros -s fiveam -e \"
              (ql:quickload :inga)
              (handler-case (asdf:test-system :inga)
                (error () (uiop:quit 1)))
              (ql:quickload :inga/test-node)
              (handler-case (asdf:test-system :inga/test-node)
                (error () (uiop:quit 1)))\""

