name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:

  test:
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      LISP: ${{ matrix.lisp }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: 40ants/setup-lisp@v2
      with:
        asdf-system: inga
    - uses: 40ants/run-tests@v2
      with:
        asdf-system: inga

  test-typescript:
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/seachicken/inga:0.1.30-pre0-typescript-build
      #env:
      #  HOME: ${{ github.workspace }}
      #options: --workdir ${{ github.workspace }} --env HOME=${{ github.workspace }}

    steps:
    - name: Install git
      run: |
        apt install -y git
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Checkout submodules
      run: |
        ls -lsa .
        git submodule update --init
    - name: Run tests
      run: |
        ls -lsa test/fixtures/react-typescript-todo
        ros -e '(handler-bind ((error (lambda (c) (print c) (uiop:quit 1))))
                  (asdf:load-system :inga)
                  (asdf:test-system :inga/test-typescript))'

