name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:

  test-typescript:
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/seachicken/inga:latest-typescript

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        apt install -y sudo bzip2
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Install fiveam
      run: ros install fiveam
    - name: Run tests
      run: |
        ros -s fiveam -e "(asdf:test-system :inga)
                          (asdf:load-system :inga/test-typescript)
                          (or (fiveam:run! (uiop:find-symbol* '#:typescript
                                                              :inga/test/parser/typescript))
                              (uiop:quit 1))"

